### PR TITLE
[Feature] Added a rectangle component

### PR DESCRIPTION
**Pull request by Mrredstone5230**
Added a rectangle component. Accepts position, size, but also optionally color, and filled tags. (If filled set to true, the rectangle will be filled (default). If not, only the border of the rectangle will be drawn.)

(All fields can accept templates)

Example usage:
```yaml
page_type: components
components:
  - type: rectangle
    position:
      - 4
      - "{{ states('input_number.kml') }}"
    size:
      - "{{ states('input_number.kml') }}"
      - 6
    color: yellow
    filled: "{{ states('input_number.kml')|int >= 5 }}"

```

### CODE REVIEW

**Comment by gickowtf** [comment]
Hey that's funny I really wanted to add something again and had already thought about the rectangle last night ... You were faster 👍 I'll merge your two PR tonight

**Comment by gickowtf** [comment]
> Added a rectangle component. Accepts position, size, but also optionally color, and filled tags. (If filled set to true, the rectangle will be filled (default). If not, only the border of the rectangle will be drawn.)
> 
> (All fields can accept templates)
> 
> Example usage:
> 
> ```yaml
> page_type: components
> components:
>   - type: rectangle
>     position:
>       - 4
>       - "{{ states('input_number.kml') }}"
>     size:
>       - "{{ states('input_number.kml') }}"
>       - 6
>     color: yellow
>     filled: "{{ states('input_number.kml')|int >= 5 }}"
> ```

last time I answered in the wrong PR... I've fixed it now, I just thought that because templates are used in your example here that it would also work ... I think that was probably a mistake in my mind.

**Comment by Mrredstone5230** [comment]
> > Added a rectangle component. Accepts position, size, but also optionally color, and filled tags. (If filled set to true, the rectangle will be filled (default). If not, only the border of the rectangle will be drawn.)
> 
> > 
> 
> > (All fields can accept templates)
> 
> > 
> 
> > Example usage:
> 
> > 
> 
> > ```yaml
> 
> > page_type: components
> 
> > components:
> 
> >   - type: rectangle
> 
> >     position:
> 
> >       - 4
> 
> >       - "{{ states('input_number.kml') }}"
> 
> >     size:
> 
> >       - "{{ states('input_number.kml') }}"
> 
> >       - 6
> 
> >     color: yellow
> 
> >     filled: "{{ states('input_number.kml')|int >= 5 }}"
> 
> > ```
> 
> 
> 
> last time I answered in the wrong PR... I've fixed it now, I just thought that because templates are used in your example here that it would also work ... I think that was probably a mistake in my mind. 

They didn't work before you fix?? I though it did..

**Comment by Mrredstone5230** [comment]
Ohh I see what could have happened. I think the first element of the lists didn't have the variables working, but the second did. Sorry about this...

**Comment by gickowtf** [comment]
Unfortunately not. But everything is fine now. I only noticed it when I rewrote the progressbar as a component for a readme.

https://github.com/gickowtf/pixoo-homeassistant/blob/main/READMES/progressbar.md

**Pull request merged**
