### PR TITLE
Feature: text align

### PR DESCRIPTION
**Pull request by entrhopi**
Hello!

I've added rudimentary support for text alignment.
A new value for the text component has been added:
`align = left,right,center`

If the value is other than `left` the `draw_text` function will calculate the (pixel)length of the text and adjust the position accordingly.

Currently, this only works for single line text. I will revisit this in the future if nobody else is faster.

`README` has also been updated.

### CODE REVIEW

**Comment by gickowtf** [comment]
Hey thanks a lot for your effort. Give me a little time to check and test the whole thing :D

**Comment by entrhopi** [comment]
Sure! Feedback is appreciated! Especially because my set of tests is very limited, and I'm always blind to the apparent errors. xD
I might have some time today to tackle the multiline handling too.

**Comment by entrhopi** [comment]
Multiline support has also been added.

**Comment by gickowtf** [comment]
Many many thanks 🚀

**Pull request merged**
