### PR TITLE
Moving the configuration to the Config Flow

### PR DESCRIPTION
**Pull request by Mrredstone5230**
Alright, So I was a little bored, so I basically upgraded the whole integration to use the config flows for fun. (and to patch some various issues) Now, the whole integration can be configured through the HA UI, which is SOOO much better than having to restart the whole instance every time you want to make a little change. Plus, this also supports multiple devices (technically, at least I hope).

Although I originally tried to keep the original configuration file from working, I realized it was just annoying more than anything, so I completely removed it, as it would become a very useless feature anyways. 

Please edit this as you like. Thanks for all!

### CODE REVIEW

**Comment by Mrredstone5230** [comment]
Just noticed that if this gets accepted, it will probably need an update of the README...

**Comment by gickowtf** [comment]
Hey, iam sorry for the late answer. I will test your Pull in the next days and give you an answer... Thanks 4 Support

**Comment by gickowtf** [comment]
@Mrredstone5230 
I am thrilled. Good work... at first I couldn't imagine what the configuration in the config flow should look like. But this is to my taste! Accordingly, the adaptation of the readme is not as much as expected. You also implemented the notifications really well, thank you very much. Your second pull request with the brightness might have to be adjusted when I merge the first one? 
I'll try to merge it at the weekend. I just have to remember to tell the users to delete the integration before the update and to save the config beforehand :D
I will also mention you in the readme if you wish.

**Comment by Mrredstone5230** [comment]
> @Mrredstone5230 I am thrilled. Good work... at first I couldn't imagine what the configuration in the config flow should look like. But this is to my taste! Accordingly, the adaptation of the readme is not as much as expected. You also implemented the notifications really well, thank you very much. Your second pull request with the brightness might have to be adjusted when I merge the first one? I'll try to merge it at the weekend. I just have to remember to tell the users to delete the integration before the update and to save the config beforehand :D I will also mention you in the readme if you wish.

Great, I'm glad you like it. I just fixed the typo so the tests pass. And a mention would be nice, (if possible of course 🙂).

> Your second pull request with the brightness might have to be adjusted when I merge the first one?

I don't think it would need to be adjusted, but we'll see. I think it would be better to merge it after this one though.

**Comment by Mrredstone5230** [comment]
Alright, I'm so sorry about this hassfest madness. Now it should validate correctly.

**Pull request merged**
