### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by steamEngineer**
Reformatted the entire readme to hopefully make it a bit easier to parse for people new to the integration. Also added a short section at the end to briefly touch on entity states & templates.

_Edit: pretty new to using github. So apologies on any issues with the way I set up the pull request. I pretty much left the pull/fork at the default github settings_

### CODE REVIEW

**Comment by gickowtf** [comment]
all in all, i like it very much :D

**Comment by gickowtf** [comment]
ok i have fixed it

**Comment by steamEngineer** [comment]
Glad you liked it!

**Comment by steamEngineer** [comment]
The fixes make complete sense, appreciate you reviewing and incorporating them!

**Pull request merged**
